/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  migchav
 * Created: 11 abr. 2022
 */

drop table OBTENCIONSUSCRIPCION;
drop table SUSCRIPCION;
drop table DESARROLLOCURSO;
drop table DESARROLLOSECCION;
drop table CURSOFAVORITO;
drop table SECCION;
drop table CURSO;
drop table CATEGORIA;
drop table USUARIO;

create table CATEGORIA (
    NOMBRE varchar(50),

    PRIMARY KEY(NOMBRE)
);

create table USUARIO (
    ID INTEGER  AUTO_INCREMENT,
    NOMBREUSUARIO varchar(50) NOT NULL,
    CONTRASEÑA varchar(50) NOT NULL,
    CORREO varchar(50) NOT NULL,
    NOMBRE varchar(50),
    APELLIDO varchar(50),
    TELEFONO int,
    INSTRUCTOR boolean,
    DIRECCION varchar(50),
    OCUPACION varchar(50),
    PAIS varchar(50),
    CIUDAD varchar(50),
    FECHANACIMIENTO date,
    BIOGRAFIA varchar(200),
    
    PRIMARY KEY(ID)
);

create table CURSO (
    ID INTEGER AUTO_INCREMENT,
    NOMBRE varchar(50) NOT NULL,
    DESCRIPCION varchar(50) NOT NULL,
    PRECIO float NOT NULL,
    IMAGEN varchar(200) NOT NULL,
    DURACION float NOT NULL,
    CATEGORIA varchar(50) NOT NULL,
    CREADOR INTEGER NOT NULL,
    
    PRIMARY KEY(ID),
    FOREIGN KEY(CREADOR) REFERENCES USUARIO(ID),
    FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIA(NOMBRE)
);

create table DESARROLLOCURSO (
    VALORACION double,
    FECHAINICIO date,
    IDUSUARIO INTEGER,
    IDCURSO INTEGER,
    PRIMARY KEY(FECHAINICIO, IDUSUARIO, IDCURSO),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (IDCURSO) REFERENCES CURSO(ID)
);

create table CURSOFAVORITO (
    IDUSUARIO INTEGER,
    IDCURSO INTEGER,

    PRIMARY KEY(IDUSUARIO, IDCURSO),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY(IDCURSO) REFERENCES CURSO(ID)
);

create table SECCION (
    ID INTEGER AUTO_INCREMENT,
    NOMBRE varchar(50) ,
    DESCRIPCION varchar(50),
    VIDEO varchar(50) NOT NULL,
    DURACION float NOT NULL,
    IDCURSO INTEGER,

    PRIMARY KEY(ID),
    FOREIGN KEY(IDCURSO) REFERENCES CURSO(ID)
);

create table DESARROLLOSECCION (
    IDSECCION INTEGER,
    IDUSUARIO INTEGER,
    COMPLETADA boolean,

    PRIMARY KEY(IDSECCION, IDUSUARIO),
    FOREIGN KEY(IDSECCION) REFERENCES SECCION(ID),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID)
);

create table SUSCRIPCION (
    ID INTEGER AUTO_INCREMENT,
    TIPO ENUM('GRATIS','AUTOR','TOTAL','ESTUDIANTE') NOT NULL,
    PRECIO FLOAT NOT NULL,
    IDAUTOR INTEGER,

    PRIMARY KEY(ID),
    FOREIGN KEY(IDAUTOR) REFERENCES USUARIO(ID)
);

create table OBTENCIONSUSCRIPCION (
    FECHAINICIO date NOT NULL,
    COBRO ENUM('MENSUAL','ANUAL') NOT NULL,
    AUTORENOVAR boolean NOT NULL,
    IDUSUARIO INTEGER,
    IDSUSCRIPCION INTEGER,

    PRIMARY KEY(IDUSUARIO, IDSUSCRIPCION, FECHAINICIO),
    FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY(IDSUSCRIPCION) REFERENCES SUSCRIPCION(ID)
);




